sudo: false
language: node_js
install:
- NODE_ENV=development npm install
before_script:
- make build
script:
- travis-lint .travis.yml
- make eslint
- make stylint
- npm test
# cache:
#   directories:
#   - node_modules
env:
- NODE_ENV=production
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: bdYCPOgURi5LgUx2L/PliWNFRTZAJjLNXR8fGZ6/J3o5sTNdHIuqmMMAxVhgN3Qp1WpZt9aFDcYeBfWwmEhfNDUafLDmjuGaya0FnQ4dONS1FGWQCSPolT7uwrAbYG933WvypgE0XlI52QHZ+2nL0vFrM7Douqla+VNBEfoO04g=
  app:
    secure: Fl1NNHj018HMaSYwzc9zpl+1jrxip4J8pYshVkPnUExhRQBKS+NU3f7Krh1lnRKZTAHAlOkZLLrU6EjYGDnNZeruGHRdR9GwNND4MoNSOf5aQJc3SyIsqfuvHYRB+dMfuGMXWPGS6ZiNEh2imWE7bFvvYc6CtgyzSBiGv4Mb+U8=
